name: ci-fullcycle-desafio-workflow

on: 
  pull_request:
    branches:
      - develop

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['20']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install

      - run: npm test
      - run: node ./src/index.js

      - name: Set up QEMU # responsável por rodar o Docker em diversas arquiteturas
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx # responsável por fazer o build do Dockerfile
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub # Realiza o login em nossa conta do Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push # Neste step ele faz o build e o push(se estiver true) para o dockerhub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: mdvedovato/fullcycle-desafio-ci-node:latest  # Substitua pela sua tag correta no DockerHub

